baseURL = "https://ronnyroethof.nl/"
title = "Ronny Roethof"
#googleAnalytics = ""
 
enableRobotsTXT = true
enableEmoji = true

theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

languageCode = "nl-nl"
defaultContentLanguage = "nl"
defaultContentLanguageInSubdir = true
disableDefaultLanguageRedirect = false

[languages]
  [languages.nl]
    languageCode = "nl-NL"
    languageName = "Nederlands"
    weight = 1

  [languages.nl.params]
    cv_pdf = "/pdf/ronny-roethof-cv-nl.pdf"

  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    weight = 2

  [languages.en.params]
    cv_pdf = "/pdf/ronny-roethof-cv-en.pdf"


[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#98D2EB"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#98D2EB"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#98D2EB"
pages = 4
# Set this param to 'true' to swap the bar positions
swapColumns = false
